export { default as Homepage } from "./Homepage"
export { default as About } from "./About"
export { default as Courses } from "./Courses"
export { default as Trainers } from "./Trainers"
export { default as Events } from "./Events"
export { default as Pricing } from "./Pricing"
export { default as Contact } from "./Contact"
export {default as LoginForm} from "../../components/templates/auth/LoginForm"
export { default as CourseDetail } from "./CourseDetail"
export {default as UserBody} from "../../components/Admin/User/UserBody"
export {default as AddNewStaff} from "../../components/Admin/Staff/AddNewStaff"
export {default as MentorBody} from "../../components/Admin/Mentor/MentorBody"
export {default as AdminDashboard} from "../../modules/mainPage/Admin/AdminDashboard"
export {default as UpdateMentorForm} from "../../components/Admin/Mentor/UpdateMentorForm"
export {default as UpdateStaffForm} from "../../components/Admin/Staff/UpdateStaffForm"
export {default as StudentBody} from "../../components/Admin/Student/StudentBody"
export {default as StaffBody} from "../../components/Admin/Staff/StaffBody"